/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  account_id: string;
  account_type: string;
  base_currency: string;
  customer_id: string;
  opened_at: string;
  provider: string;
  status: string;
}

export interface Customers {
  city: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  date_of_birth: string;
  email: string;
  full_name: string;
  kyc_status: string;
  onboarded_at: string;
  phone: string;
  segment: string;
  state: string;
}

export interface Goals {
  created_at: Generated<Timestamp>;
  current_funded_amount: Numeric;
  customer_id: string;
  goal_id: Generated<string>;
  goal_name: string;
  goal_type: string;
  priority: string;
  target_amount: Numeric;
  target_date: string;
  updated_at: Generated<Timestamp>;
}

export interface Holdings {
  account_id: string;
  avg_cost: Numeric;
  instrument_id: string;
  quantity: Numeric;
  snapshot_date: string;
}

export interface ImportBatches {
  accepted_rows: number;
  batch_id: Generated<Int8>;
  dataset: string;
  file_name: string;
  file_sha256: string;
  finished_at: Generated<Timestamp>;
  rejected_rows: number;
  started_at: Timestamp;
  total_rows: number;
  uploaded_by: Int8 | null;
}

export interface ImportRejects {
  batch_id: Int8;
  line_number: number;
  raw_row: Json;
  reason_code: string;
  reasons: Json;
  record_key: string | null;
}

export interface Instruments {
  asset_class: string;
  currency: string;
  exchange: string;
  instrument_id: string;
  instrument_name: string;
  last_price: Numeric;
  price_as_of: string;
  risk_band: string;
  sector: string | null;
  symbol: string;
}

export interface RiskProfiles {
  assessed_at: string;
  customer_id: string;
  horizon_years: number;
  liquidity_need: string;
  risk_level: string;
  risk_score: number;
}

export interface SchemaMigrations {
  version: string;
}

export interface Transactions {
  account_id: string;
  amount: Numeric;
  created_at: Generated<Timestamp>;
  instrument_id: string;
  price: Numeric;
  quantity: Numeric;
  status: string;
  trade_date: string;
  transaction_id: string;
  transaction_type: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string;
  password_hash: string;
  role: string;
  user_id: Generated<Int8>;
}

export interface VAccountValuation {
  account_id: string | null;
  account_type: string | null;
  base_currency: string | null;
  cost_basis: Numeric | null;
  customer_id: string | null;
  market_value: Numeric | null;
  opened_at: string | null;
  position_count: number | null;
  price_as_of: string | null;
  provider: string | null;
  snapshot_date: string | null;
  status: string | null;
  unrealised_pnl: Numeric | null;
}

export interface VAssetAllocation {
  asset_class: string | null;
  customer_id: string | null;
  market_value: Numeric | null;
  weight_pct: Numeric | null;
}

export interface VCustomerPortfolio {
  account_count: number | null;
  cost_basis: Numeric | null;
  customer_id: string | null;
  market_value: Numeric | null;
  position_count: number | null;
  price_as_of: string | null;
  snapshot_date: string | null;
  unrealised_pnl: Numeric | null;
}

export interface VDataQualityExceptions {
  customer_id: string | null;
  detail: string | null;
  entity: string | null;
  entity_id: string | null;
  exception_type: string | null;
}

export interface VGoalStatus {
  created_at: Timestamp | null;
  current_funded_amount: Numeric | null;
  customer_id: string | null;
  funded_pct: Numeric | null;
  goal_id: string | null;
  goal_name: string | null;
  goal_type: string | null;
  is_high_priority_underfunded: boolean | null;
  is_name_type_mismatch: boolean | null;
  is_overdue: boolean | null;
  is_overfunded: boolean | null;
  priority: string | null;
  target_amount: Numeric | null;
  target_date: string | null;
  updated_at: Timestamp | null;
}

export interface VLatestRiskProfile {
  assessed_at: string | null;
  customer_id: string | null;
  horizon_years: number | null;
  liquidity_need: string | null;
  risk_level: string | null;
  risk_score: number | null;
}

export interface VMonthlyNetFlows {
  buy_amount: Numeric | null;
  month: string | null;
  net_invested: Numeric | null;
  sell_amount: Numeric | null;
  trade_count: number | null;
}

export interface VPositions {
  account_id: string | null;
  account_status: string | null;
  account_type: string | null;
  asset_class: string | null;
  avg_cost: Numeric | null;
  cost_basis: Numeric | null;
  customer_id: string | null;
  instrument_id: string | null;
  instrument_name: string | null;
  last_price: Numeric | null;
  market_value: Numeric | null;
  price_as_of: string | null;
  quantity: Numeric | null;
  snapshot_date: string | null;
  symbol: string | null;
  unrealised_pnl: Numeric | null;
}

export interface DB {
  accounts: Accounts;
  customers: Customers;
  goals: Goals;
  holdings: Holdings;
  import_batches: ImportBatches;
  import_rejects: ImportRejects;
  instruments: Instruments;
  risk_profiles: RiskProfiles;
  schema_migrations: SchemaMigrations;
  transactions: Transactions;
  users: Users;
  v_account_valuation: VAccountValuation;
  v_asset_allocation: VAssetAllocation;
  v_customer_portfolio: VCustomerPortfolio;
  v_data_quality_exceptions: VDataQualityExceptions;
  v_goal_status: VGoalStatus;
  v_latest_risk_profile: VLatestRiskProfile;
  v_monthly_net_flows: VMonthlyNetFlows;
  v_positions: VPositions;
}
